import puppeteer from 'puppeteer';
import fs from 'fs';
import path from 'path';
import { v4 as uuidv4 } from 'uuid';
import { VideoScript } from '../prompts';

/**
 * Generate images for each scene in the script
 */
export async function generateSlideImages(script: VideoScript): Promise<string[]> {
    const browser = await puppeteer.launch({
        headless: true, // "new" is deprecated, usually true works
        args: ['--no-sandbox', '--disable-setuid-sandbox'],
        timeout: 60000 // Increase browser timeout
    });
    const page = await browser.newPage();
    await page.setViewport({ width: 1920, height: 1080 });
    // Increase navigation timeout
    page.setDefaultNavigationTimeout(60000);

    const tempDir = path.join(process.cwd(), 'public', 'temp');
    if (!fs.existsSync(tempDir)) {
        fs.mkdirSync(tempDir, { recursive: true });
    }

    const imagePaths: string[] = [];

    try {
        for (const scene of script.scenes) {
            const htmlContent = getHtmlTemplate(scene.visual, scene.textOverlay);
            // Use domcontentloaded for faster rendering, relying on static HTML
            await page.setContent(htmlContent, { waitUntil: 'domcontentloaded' });

            const fileName = `${uuidv4()}.png`;
            const filePath = path.join(tempDir, fileName);

            await page.screenshot({ path: filePath, type: 'png' });
            imagePaths.push(filePath);
        }
    } finally {
        await browser.close();
    }

    return imagePaths;
}

/**
 * Basic HTML Template for Video Slides
 * Using CSS gradients and nice typography
 */
function getHtmlTemplate(visualDescription: string, textOverlay: string): string {
    // Determine background style based on visual description (basic heuristic)
    // or just use a dynamic gradient for now.
    const gradient = getRandomGradient();

    return `
    <!DOCTYPE html>
    <html>
    <head>
        <style>
            body {
                margin: 0;
                padding: 0;
                width: 1920px;
                height: 1080px;
                display: flex;
                flex-direction: column;
                justify-content: center;
                align-items: center;
                background: ${gradient};
                font-family: system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
                color: white;
                text-align: center;
                box-sizing: border-box;
            }
            .content {
                background: rgba(0, 0, 0, 0.4);
                padding: 60px;
                border-radius: 30px;
                backdrop-filter: blur(10px);
                max-width: 80%;
                box-shadow: 0 20px 50px rgba(0,0,0,0.3);
            }
            h1 {
                font-size: 80px;
                margin-bottom: 20px;
                line-height: 1.2;
                font-weight: 800;
                text-shadow: 2px 2px 10px rgba(0,0,0,0.5);
            }
            p {
                font-size: 40px;
                font-weight: 400;
                opacity: 0.9;
                margin-top: 0;
            }
            .footer {
                position: absolute;
                bottom: 40px;
                font-size: 24px;
                opacity: 0.6;
            }
        </style>
    </head>
    <body>
        <div class="content">
            <h1>${textOverlay.split('\n')[0]}</h1>
            <p>${textOverlay.split('\n').slice(1).join('<br>')}</p>
        </div>
        <div class="footer">Generated by AI</div>
    </body>
    </html>
    `;
}

function getRandomGradient(): string {
    const gradients = [
        'linear-gradient(135deg, #667eea 0%, #764ba2 100%)', // Deep Purple
        'linear-gradient(135deg, #6B73FF 0%, #000DFF 100%)', // Blue
        'linear-gradient(135deg, #FF9A9E 0%, #FECFEF 99%, #FECFEF 100%)', // Pinky
        'linear-gradient(135deg, #f093fb 0%, #f5576c 100%)', // Sunset
        'linear-gradient(43deg, #4158D0 0%, #C850C0 46%, #FFCC70 100%)' // Unicorn
    ];
    return gradients[Math.floor(Math.random() * gradients.length)];
}
